#!/usr/bin/env python3

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import pandas as pd
import seaborn as sns
from matplotlib.colors import ListedColormap


CATEGORY_ORDER = {"core": 0, "accessory": 1, "singleton": 2}
CATEGORY_COLORS = {
    "core": "#0f766e",
    "accessory": "#c2410c",
    "singleton": "#7f1d1d",
}


def parse_args():
    parser = argparse.ArgumentParser(description="Plot a pangenome presence/absence heatmap.")
    parser.add_argument(
        "--presence-absence",
        type=Path,
        default=Path("results/expanded_refs/presence_absence.tsv"),
        help="Presence/absence table generated by run_pangenome.py",
    )
    parser.add_argument(
        "--genome-metadata",
        type=Path,
        default=Path("results/expanded_refs/genome_metadata.tsv"),
        help="Genome metadata table generated by run_pangenome.py",
    )
    parser.add_argument(
        "--output-prefix",
        type=Path,
        default=Path("results/expanded_refs/pangenome_presence_absence_heatmap"),
        help="Output prefix for image files",
    )
    parser.add_argument(
        "--title",
        type=str,
        default="Phage Pangenome Presence/Absence Heatmap",
        help="Figure title",
    )
    return parser.parse_args()


def shorten_name(name: str) -> str:
    name = name.replace("Klebsiella phage ", "")
    name = name.replace("Query_", "")
    return name


def load_matrix(presence_absence_path: Path, metadata_path: Path):
    pa = pd.read_csv(presence_absence_path, sep="\t")
    metadata = pd.read_csv(metadata_path, sep="\t")
    genome_order = metadata["genome_id"].tolist()
    pa = pa.assign(category_rank=pa["category"].map(CATEGORY_ORDER))
    pa = pa.assign(n_genomes_num=pa["n_genomes"].astype(int))
    pa = pa.sort_values(
        by=["category_rank", "n_genomes_num", "query_module", "consensus_product", "orthogroup"],
        ascending=[True, False, True, True, True],
    )
    matrix = (
        pa[genome_order]
        .fillna("")
        .apply(lambda col: col.map(lambda value: 1 if str(value).strip() else 0))
        .reset_index(drop=True)
    )
    pa = pa.reset_index(drop=True)
    row_labels = [
        f"{row.orthogroup} | {row.consensus_product if pd.notna(row.consensus_product) else 'unknown'}"
        for row in pa.itertuples()
    ]
    col_labels = []
    for row in metadata.itertuples():
        if row.genome_id == "query":
            col_labels.append("Query")
        else:
            col_labels.append(shorten_name(row.genome_name))
    return pa, matrix, row_labels, col_labels


def plot(pa: pd.DataFrame, matrix: pd.DataFrame, row_labels: list[str], col_labels: list[str], output_prefix: Path, title: str):
    sns.set_theme(style="white")
    n_rows = len(matrix)
    n_cols = len(matrix.columns)

    fig_width = max(13, 0.4 * n_cols + 8)
    fig_height = max(14, 0.11 * n_rows + 3.5)

    fig = plt.figure(figsize=(fig_width, fig_height), constrained_layout=True)
    gs = fig.add_gridspec(2, 3, width_ratios=[0.35, 12, 2.6], height_ratios=[18, 1.2], wspace=0.05, hspace=0.05)
    ax_cat = fig.add_subplot(gs[0, 0])
    ax = fig.add_subplot(gs[0, 1])
    ax_leg = fig.add_subplot(gs[0, 2])
    ax_note = fig.add_subplot(gs[1, :])

    category_values = pa["category"].map({"core": 0, "accessory": 1, "singleton": 2}).to_numpy().reshape(-1, 1)
    category_cmap = ListedColormap(
        [CATEGORY_COLORS["core"], CATEGORY_COLORS["accessory"], CATEGORY_COLORS["singleton"]]
    )
    ax_cat.imshow(category_values, aspect="auto", interpolation="nearest", cmap=category_cmap, vmin=0, vmax=2)
    ax_cat.set_xticks([])
    ax_cat.set_yticks([])
    ax_cat.set_title("Class", fontsize=10, pad=10)
    for spine in ax_cat.spines.values():
        spine.set_visible(False)

    sns.heatmap(
        matrix,
        ax=ax,
        cmap=sns.color_palette(["#f8fafc", "#1d4ed8"]),
        cbar=True,
        vmin=0,
        vmax=1,
        linewidths=0.15,
        linecolor="#d1d5db",
        xticklabels=col_labels,
        yticklabels=False,
        cbar_kws={"label": "Orthogroup presence", "ticks": [0, 1]},
    )
    ax.set_xlabel("Genomes", fontsize=11)
    ax.set_ylabel("Orthogroups", fontsize=11)
    ax.set_title(title, fontsize=14, pad=12)
    ax.tick_params(axis="x", labelrotation=90, labelsize=8)

    core_n = (pa["category"] == "core").sum()
    accessory_n = (pa["category"] == "accessory").sum()
    singleton_n = (pa["category"] == "singleton").sum()
    if core_n:
        ax.axhline(core_n, color="#0f172a", linewidth=1.0)
    if core_n + accessory_n:
        ax.axhline(core_n + accessory_n, color="#0f172a", linewidth=1.0)

    ax.text(
        0.01,
        1.02,
        f"{n_cols} genomes, {n_rows} orthogroups",
        transform=ax.transAxes,
        fontsize=10,
        ha="left",
        va="bottom",
    )

    legend_handles = [
        mpatches.Patch(color=CATEGORY_COLORS["core"], label=f"Core ({core_n})"),
        mpatches.Patch(color=CATEGORY_COLORS["accessory"], label=f"Accessory ({accessory_n})"),
        mpatches.Patch(color=CATEGORY_COLORS["singleton"], label=f"Singleton ({singleton_n})"),
    ]
    ax_leg.axis("off")
    ax_leg.legend(handles=legend_handles, loc="upper left", frameon=False, title="Orthogroup class")

    ax_note.axis("off")
    ax_note.text(
        0.0,
        0.5,
        "Rows are ordered by orthogroup class and prevalence; columns follow the cohort genome order.",
        fontsize=9,
        ha="left",
        va="center",
    )

    png_path = output_prefix.with_suffix(".png")
    tiff_path = output_prefix.with_suffix(".tiff")
    fig.savefig(png_path, dpi=400)
    fig.savefig(tiff_path, dpi=400)
    plt.close(fig)


def main():
    args = parse_args()
    pa, matrix, row_labels, col_labels = load_matrix(args.presence_absence, args.genome_metadata)
    plot(pa, matrix, row_labels, col_labels, args.output_prefix, args.title)


if __name__ == "__main__":
    main()
